// Internal link crawler and source scanner.
//
//   npm run check-links                       (server on http://localhost:3000)
//   BASE_URL=http://localhost:3000 npm run check-links
//   npm run check-links -- --base-url=https://etriplesoft.com
//   npm run check-links -- --static-only      (source checks only, no server)
//   npm run check-links -- --json[=reports/link-check.json]
//   npm run check-links -- --strict           (warnings also fail)
//   npm run check-links -- --allow-localhost  (local test setups only)
//
// Exit codes: 0 pass, 1 errors found, 2 usage or server unreachable.
//
// Rendered mode starts from the sitemap (built from the same data as the
// pages) and follows every first-party link. Redirect sources come from
// src/lib/redirects.ts, the single redirect map. External links are only
// syntax-checked, never fetched, so third-party outages cannot fail the run.
import { existsSync } from "node:fs";
import { activeRedirects } from "../src/lib/redirects.ts";
import { localizedInsightSlugs, localizedLegacyInsightSlugs, localizedPortfolioProjectSlugs, localizedRoutePaths } from "../src/i18n/localized-paths.ts";
import { legacyDrafts } from "../src/content/insights/drafts.ts";
import { arabicLegacyDrafts } from "../src/content/insights-ar/legacy-drafts.ts";
import { allowlist, builtinFragments, forbiddenHostPatterns, forbiddenHosts, trackingParams } from "./lib/qa-config.mjs";
import { PROD_HOSTS, PROD_ORIGIN, Reporter, extract, follow, parseArgs, pool, rebase, request, writeJson } from "./lib/qa.mjs";
import { appRoutes, articleSlugs, catchAllSlugs, duplicateRoutes, scanSource } from "./lib/static-scan.mjs";

const args = parseArgs();
const { base } = args;
const strict = args.flags.has("strict");
const allowLocalhost = args.flags.has("allow-localhost");
const staticOnly = args.flags.has("static-only");
const report = new Reporter();

const redirectSources = new Map();
for (const { source, destination } of activeRedirects) {
  redirectSources.set(source, destination);
  redirectSources.set(source + "/", destination);
}
const legacy = (path) => redirectSources.get(path) ?? redirectSources.get(path.replace(/\/$/, ""));

const isForbiddenHost = (host) => forbiddenHosts.includes(host) || forbiddenHostPatterns.some((p) => p.test(host));
const allowed = (type, source, target) =>
  allowlist.some((a) => a.type === type && (!a.source || a.source === source) && (!a.target || a.target === target));
const add = (type, severity, fields) => {
  if (allowed(type, fields.source, fields.target)) return;
  report.add(type, severity, fields);
};

// ---------------------------------------------------------------- static
const summary = { staticRoutes: 0, dynamicRoutes: 0, filesScanned: 0 };
{
  const routes = appRoutes();
  summary.staticRoutes = routes.filter((r) => !r.dynamic).length + catchAllSlugs().length;
  summary.dynamicRoutes = articleSlugs().length;
  const knownRoutes = new Set([
    ...routes.filter((route) => !route.dynamic).map((route) => route.route),
    ...catchAllSlugs().map(({ slug }) => `/${slug}`),
    ...articleSlugs().filter(({ kind }) => kind === "published").map(({ slug }) => `/insights/${slug}`),
    "/ar", "/ar/about-us", "/ar/contact-us", "/ar/insights",
    ...localizedRoutePaths.flatMap((path) => [path, `/ar${path}`]),
    ...localizedInsightSlugs.map((slug) => `/ar/insights/${slug}`),
    ...localizedLegacyInsightSlugs.map((slug) => `/ar/insights/${slug}`),
    ...localizedPortfolioProjectSlugs.flatMap((slug) => [`/portfolio/${slug}`, `/ar/portfolio/${slug}`]),
  ]);
  for (const slug of localizedLegacyInsightSlugs) {
    if (!legacyDrafts[slug] || !arabicLegacyDrafts[slug]) {
      add("MISSING_ARABIC_ARCHIVE_ARTICLE", "error", {
        source: `/insights/${slug}`,
        target: `/ar/insights/${slug}`,
        detail: "legacy article or its Arabic counterpart is missing",
      });
    }
  }
  for (const slug of Object.keys(legacyDrafts)) {
    if (!localizedLegacyInsightSlugs.includes(slug)) {
      add("UNPAIRED_ARCHIVE_ARTICLE", "error", {
        source: `/insights/${slug}`,
        detail: "legacy article is missing from the Arabic route inventory",
      });
    }
  }
  for (const { source, destination } of activeRedirects) {
    const target = destination.split(/[?#]/, 1)[0];
    if (knownRoutes.has(target) || existsSync(`public${target}`)) continue;
    add("REDIRECT_TARGET_NOT_FOUND", "error", {
      source,
      target,
      detail: "redirect destination is not in the public route inventory or public assets",
    });
  }
  for (const dup of duplicateRoutes())
    add("DUPLICATE_ROUTE", "error", { source: dup.route, detail: (dup.caseOnly ? "case-only duplicate; " : "") + "generated by:\n          " + dup.sources.join("\n          ") });
  const scan = scanSource({ redirectSources, forbiddenHosts, forbiddenHostPatterns });
  summary.filesScanned = scan.filesScanned;
  for (const issue of scan.issues) add(issue.type, issue.severity, { source: issue.at, target: issue.value, preferred: issue.preferred, detail: "in source" });
}

// -------------------------------------------------------------- rendered
const pages = new Map(); // path -> { ids, anchors, robots, canonical, ... }
const targetCache = new Map(); // "path?query" -> follow() result
const assetCache = new Map();
const stats = { internalLinks: 0, externalLinks: 0, mailto: 0, tel: 0, assets: 0 };
const referencedIds = new Set();

const dropTracking = (u) => {
  for (const p of trackingParams) u.searchParams.delete(p);
  return u;
};
const pathKey = (pathname) => {
  const p = decodeURI(pathname).replace(/\/+$/, "");
  return p === "" ? "/" : p;
};

function classify(href, sourcePath) {
  if (href === undefined || href.trim() === "") return { kind: "placeholder", why: "empty href" };
  const value = href.trim();
  if (value === "#") return { kind: "placeholder", why: 'href="#"' };
  if (/^javascript:/i.test(value)) return { kind: "placeholder", why: "javascript: link" };
  if (value.startsWith("#")) return { kind: "fragment", fragment: decodeURIComponent(value.slice(1)) };
  if (/^mailto:/i.test(value)) return { kind: "mailto", value };
  if (/^tel:/i.test(value)) return { kind: "tel", value };
  if (/^(sms|whatsapp|data|blob):/i.test(value)) return { kind: "skip" };
  let url;
  try {
    url = /^\/\//.test(value) ? new URL("https:" + value) : new URL(value, PROD_ORIGIN + sourcePath);
  } catch {
    return { kind: "malformed", why: "cannot be parsed as a URL" };
  }
  if (!/^https?:$/.test(url.protocol)) return { kind: "skip" };
  const absolute = /^(https?:)?\/\//i.test(value);
  const host = url.hostname.toLowerCase();
  if (absolute && isForbiddenHost(host)) return { kind: "forbidden", host, url };
  const internal = !absolute || PROD_HOSTS.has(host) || url.host === args.baseHost;
  if (!internal) return { kind: "external", url };
  const notes = [];
  if (absolute && url.protocol === "http:" && PROD_HOSTS.has(host)) notes.push("uses http:// on the https production host");
  if (absolute && host === "www.etriplesoft.com") notes.push("uses the www host; canonical is etriplesoft.com");
  if (/[A-Z]/.test(url.pathname)) notes.push("path contains uppercase characters");
  if (url.pathname.length > 1 && url.pathname.endsWith("/")) notes.push("has a trailing slash; canonical URLs have none");
  if (/\s/.test(value)) notes.push("contains whitespace");
  return { kind: "internal", url: dropTracking(url), notes, fragment: url.hash ? decodeURIComponent(url.hash.slice(1)) : "" };
}

async function loadPage(path) {
  if (pages.has(path)) return pages.get(path);
  const record = { path, ok: false };
  pages.set(path, record);
  const result = await follow(base + path, base);
  if (!result.final || result.final.status !== 200) return record;
  const type = result.final.res.headers.get("content-type") || "";
  if (!type.includes("text/html")) {
    await result.final.res.body?.cancel();
    return record;
  }
  const html = await result.final.res.text();
  Object.assign(record, extract(html), { ok: true, finalPath: pathKey(new URL(result.final.url).pathname) });
  return record;
}

function checkTarget(urlObj) {
  const key = urlObj.pathname + urlObj.search;
  if (!targetCache.has(key))
    targetCache.set(
      key,
      follow(base + key, base).then(async (result) => {
        await result.final?.res.body?.cancel();
        return result;
      }),
    );
  return targetCache.get(key);
}

async function main() {
  // Server reachable?
  try {
    const probe = await request(base + "/");
    await probe.body?.cancel();
  } catch (error) {
    console.error(`Cannot reach ${base} (${error.cause?.code || error.message}).\nStart the app (npm run build && npm start) or pass --base-url=..., or use --static-only.`);
    process.exit(2);
  }

  // Seed with the sitemap, which is generated from the real route data.
  const sitemapRes = await request(base + "/sitemap.xml");
  const sitemapXml = sitemapRes.ok ? await sitemapRes.text() : "";
  const sitemapPaths = [...sitemapXml.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => pathKey(new URL(m[1]).pathname));
  if (!sitemapPaths.length) add("SITEMAP_MISSING", "error", { source: "/sitemap.xml", detail: "sitemap.xml missing or empty; crawling from / only" });
  const seenSitemap = new Map();
  for (const p of sitemapPaths) {
    const k = p.toLowerCase();
    if (seenSitemap.has(k)) add("DUPLICATE_ROUTE", "error", { source: p, detail: `listed twice in sitemap.xml (${seenSitemap.get(k)} and ${p})` });
    seenSitemap.set(k, p);
  }

  const queue = ["/", ...sitemapPaths];
  const queued = new Set(queue);
  while (queue.length) {
    const batch = queue.splice(0, queue.length);
    await pool(batch, 8, async (path) => {
      const page = await loadPage(path);
      if (!page.ok) return;
      for (const link of page.anchors) {
        const c = classify(link.href, path);
        if (c.kind !== "internal") continue;
        const next = pathKey(c.url.pathname);
        if (!queued.has(next) && !pages.has(next) && !redirectSources.has(next) && !redirectSources.has(next + "/")) {
          queued.add(next);
          queue.push(next);
        }
      }
    });
  }
  // Redirecting internal targets are followed to their destination so the
  // destination page is known too (needed for anchor checks).
  for (const [path, page] of [...pages]) if (!page.ok) pages.delete(path);

  // --------------------------------------------------------- per page
  const linkChecks = [];
  for (const [path, page] of pages) {
    const seenPairs = new Set();
    const idCount = new Map();
    for (const id of page.ids) idCount.set(id, (idCount.get(id) || 0) + 1);
    page.duplicateIds = [...idCount].filter(([, n]) => n > 1).map(([id]) => id);

    if (page.canonical && !page.canonical.startsWith(PROD_ORIGIN))
      add("PREVIEW_URL_IN_METADATA", "error", { source: path, target: page.canonical, detail: "canonical is not on the production origin" });
    for (const [field, value] of page.metaUrls) {
      let host;
      try {
        host = new URL(value, PROD_ORIGIN).hostname.toLowerCase();
      } catch {
        continue;
      }
      if (isForbiddenHost(host)) {
        const preview = forbiddenHostPatterns.some((p) => p.test(host));
        add(preview ? "PREVIEW_URL_IN_METADATA" : "LOCALHOST_REFERENCE", allowLocalhost && !preview ? "info" : "error", { source: path, field, target: value });
      }
    }
    for (const json of page.jsonLd) {
      for (const m of json.matchAll(/https?:\/\/([a-z0-9.-]+)(?::\d+)?[^"\\]*/gi)) {
        const host = m[1].toLowerCase();
        if (isForbiddenHost(host)) add(/localhost|127\.|0\.0\.0\.0/.test(host) ? "LOCALHOST_REFERENCE" : "PREVIEW_URL_IN_METADATA", allowLocalhost ? "info" : "error", { source: path, field: "structured data", target: m[0] });
      }
    }

    for (const link of page.anchors) {
      const pair = `${link.href}|${link.text}`;
      if (seenPairs.has(pair)) continue;
      seenPairs.add(pair);
      const c = classify(link.href, path);
      const base0 = { source: path, text: link.text, href: link.href ?? "(none)", target: link.href };
      switch (c.kind) {
        case "placeholder":
          add("PLACEHOLDER_LINK", "error", { ...base0, detail: c.why });
          break;
        case "malformed":
          add("MALFORMED_URL", "error", { ...base0, detail: c.why });
          break;
        case "forbidden":
          add(/localhost|127\.|0\.0\.0\.0/.test(c.host) ? "LOCALHOST_REFERENCE" : "STAGING_REFERENCE", allowLocalhost ? "info" : "error", { ...base0, field: "href", target: link.href });
          break;
        case "mailto":
          stats.mailto++;
          if (!/^mailto:[^\s@,?]+@[^\s@,?]+\.[^\s@,?]+(\?.*)?$/i.test(c.value)) add("BAD_MAILTO", "error", { ...base0, detail: "not a valid mailto: address" });
          break;
        case "tel":
          stats.tel++;
          if (!/^tel:\+?[\d-]{5,}$/i.test(c.value)) add("BAD_TEL", "error", { ...base0, detail: "tel: must be digits with an optional leading +, no spaces or text" });
          break;
        case "external":
          stats.externalLinks++;
          break;
        case "fragment":
          stats.internalLinks++;
          linkChecks.push({ kind: "anchor", base0, page: path, fragment: c.fragment });
          break;
        case "internal":
          stats.internalLinks++;
          linkChecks.push({ kind: "url", base0, page: path, c });
          break;
      }
    }

    for (const src of page.assetUrls) {
      let u;
      try {
        u = new URL(src, PROD_ORIGIN);
      } catch {
        continue;
      }
      if (isForbiddenHost(u.hostname.toLowerCase())) {
        add(/localhost|127\.|0\.0\.0\.0/.test(u.hostname) ? "LOCALHOST_REFERENCE" : "STAGING_REFERENCE", allowLocalhost ? "info" : "error", { source: path, field: "asset", target: src });
        continue;
      }
      const internal = !/^(https?:)?\/\//.test(src) || PROD_HOSTS.has(u.hostname) || u.host === args.baseHost;
      if (!internal || u.pathname.startsWith("/_next/image") || src.startsWith("data:")) continue;
      const key = u.pathname;
      if (!assetCache.has(key)) assetCache.set(key, { sources: new Set() });
      assetCache.get(key).sources.add(path);
    }
  }

  // ------------------------------------------------------- link status
  await pool(linkChecks, 8, async (check) => {
    if (check.kind === "anchor") {
      const page = pages.get(check.page);
      referencedIds.add(`${check.page}#${check.fragment}`);
      if (!check.fragment) return;
      if (!page.ids.includes(check.fragment) && !builtinFragments.has(check.fragment)) {
        const ci = page.ids.find((id) => id.toLowerCase() === check.fragment.toLowerCase());
        add("MISSING_ANCHOR", "error", { ...check.base0, target: `${check.page}#${check.fragment}`, detail: `Anchor "${check.fragment}" not found${ci ? ` (case mismatch: "${ci}" exists)` : ""}.` });
      }
      return;
    }
    const { c, base0, page } = check;
    const target = c.url.pathname + c.url.search;
    const targetPath = pathKey(c.url.pathname);
    const result = await checkTarget(c.url);
    const at = { ...base0, target };
    const legacyDest = legacy(c.url.pathname);
    if (result.loop) return add("REDIRECT_LOOP", "error", { ...at, chain: result.chain });
    if (result.tooMany) return add("REDIRECT_CHAIN", "error", { ...at, chain: result.chain, detail: "more than 10 redirects" });
    if (result.final.status >= 400) {
      return add(result.final.status === 404 || result.final.status === 410 ? "INTERNAL_404" : "INTERNAL_5XX", "error", { ...at, status: result.final.status });
    }
    if (result.chain.length >= 2) return add("REDIRECT_CHAIN", "error", { ...at, chain: [...result.chain.map((h) => `${h.status} ${h.url.replace(base, "")} -> ${h.location}`), `${result.final.status} ${result.final.url.replace(base, "")}`] });
    if (result.chain.length === 1) {
      const finalPath = new URL(result.final.url).pathname;
      if (legacyDest) add("LEGACY_INTERNAL_LINK", "error", { ...at, preferred: legacyDest, detail: "known legacy URL from the redirect map" });
      else add("INTERNAL_LINK_REDIRECT", "warning", { ...at, final: finalPath, detail: `${result.chain[0].status} redirect` });
    } else {
      for (const note of c.notes) add("NON_CANONICAL_URL", "warning", { ...at, detail: note });
      const landed = pages.get(targetPath);
      if (landed?.ok && /noindex/i.test(landed.robots || "")) add("LINK_TO_NOINDEX", "warning", { ...at, detail: "target page is noindex" });
    }
    if (c.fragment) {
      const finalPath = pathKey(new URL(result.final.url).pathname);
      const dest = pages.get(finalPath) ?? (await loadPage(finalPath));
      referencedIds.add(`${finalPath}#${c.fragment}`);
      if (dest.ok && !dest.ids.includes(c.fragment) && !builtinFragments.has(c.fragment)) {
        const ci = dest.ids.find((id) => id.toLowerCase() === c.fragment.toLowerCase());
        add("MISSING_ANCHOR", "error", { ...at, target: `${finalPath}#${c.fragment}`, detail: `Anchor "${c.fragment}" not found${ci ? ` (case mismatch: "${ci}" exists)` : ""}.` });
      }
    }
  });

  // Duplicate IDs: error when a link targets one, otherwise a warning.
  for (const [path, page] of pages)
    for (const id of page.duplicateIds)
      add("DUPLICATE_ID", referencedIds.has(`${path}#${id}`) ? "error" : "warning", { source: path, target: `#${id}`, detail: "id used more than once on the page" });

  // ------------------------------------------------------------ assets
  await pool([...assetCache], 12, async ([path, info]) => {
    stats.assets++;
    let res = await request(base + path, { method: "HEAD" });
    if (res.status === 405 || res.status === 501) res = await request(base + path);
    await res.body?.cancel();
    if (res.status >= 400) add("MISSING_ASSET", "error", { source: [...info.sources][0], target: path, status: res.status, detail: info.sources.size > 1 ? `also used on ${info.sources.size - 1} other page(s)` : "" });
  });
}

// ---------------------------------------------------------------- output
const format = (i) => {
  const lines = [`${i.severity.toUpperCase().padEnd(7)} ${i.type}`];
  if (i.source) lines.push(`  Source:    ${i.source}`);
  if (i.text) lines.push(`  Link text: "${i.text}"`);
  if (i.field) lines.push(`  Field:     ${i.field}`);
  if (i.href && i.href !== i.target) lines.push(`  Href:      ${i.href}`);
  if (i.target) lines.push(`  Target:    ${i.target}`);
  if (i.preferred) lines.push(`  Preferred: ${i.preferred}`);
  if (i.final) lines.push(`  Final:     ${i.final}`);
  if (i.status) lines.push(`  Status:    ${i.status}`);
  if (i.chain) lines.push(`  Chain:\n    ${i.chain.map((h) => (typeof h === "string" ? h : `${h.status} ${h.url.replace(base, "")} -> ${h.location}`)).join("\n    ")}`);
  if (i.detail) lines.push(`  ${i.detail}`);
  return lines.join("\n");
};

if (!staticOnly) await main();
report.print(format);

const n = (type) => report.count(type);
console.log("Summary");
console.log("-------");
if (!staticOnly) console.log(`Routes crawled: ${pages.size} (base ${base})`);
console.log(`Route definitions: ${summary.staticRoutes} static, ${summary.dynamicRoutes} article slugs; source files scanned: ${summary.filesScanned}`);
if (!staticOnly) console.log(`Internal links checked: ${stats.internalLinks}; assets: ${stats.assets}; mailto: ${stats.mailto}; tel: ${stats.tel}; external (syntax only): ${stats.externalLinks}`);
console.log(`\nErrors:
  404 / 5xx links:      ${n("INTERNAL_404") + n("INTERNAL_5XX")}
  missing anchors:      ${n("MISSING_ANCHOR")}
  duplicate ids used:   ${report.issues.filter((i) => i.type === "DUPLICATE_ID" && i.severity === "error").length}
  duplicate routes:     ${n("DUPLICATE_ROUTE")}
  redirect chains/loops:${n("REDIRECT_CHAIN") + n("REDIRECT_LOOP")}
  placeholder links:    ${n("PLACEHOLDER_LINK")}
  legacy internal links:${n("LEGACY_INTERNAL_LINK")}
  localhost/preview:    ${n("LOCALHOST_REFERENCE") + n("PREVIEW_URL_IN_METADATA") + n("STAGING_REFERENCE") - report.warnings.filter((i) => i.type === "STAGING_REFERENCE").length}
  bad mailto/tel/url:   ${n("BAD_MAILTO") + n("BAD_TEL") + n("MALFORMED_URL")}
  missing assets:       ${n("MISSING_ASSET")}
Warnings:
  redirecting internal links: ${n("INTERNAL_LINK_REDIRECT")}
  non-canonical URL format:   ${n("NON_CANONICAL_URL")}
  links to noindex pages:     ${n("LINK_TO_NOINDEX")}
  duplicate ids (unlinked):   ${report.issues.filter((i) => i.type === "DUPLICATE_ID" && i.severity === "warning").length}
`);
const failed = report.errors.length > 0 || (strict && report.warnings.length > 0);
console.log(`Result: ${failed ? "FAILED" : report.warnings.length ? "PASSED with warnings" : "PASSED"}`);
if (args.json) {
  writeJson(args.jsonPath || "reports/link-check.json", { base, generatedAt: new Date().toISOString(), summary: { pages: pages.size, ...stats, ...summary, errors: report.errors.length, warnings: report.warnings.length }, issues: report.issues });
}
// Set the code instead of process.exit(): exiting with sockets still open
// crashes Node on Windows (libuv assertion).
process.exitCode = failed ? 1 : 0;
