import { defineOdooPage } from "../child/renderable";
import {
  accountingMetadata,
  anchors,
  closing,
  comparison,
  control,
  core,
  einvoicing,
  faqs,
  hero,
  implementation,
  integrations,
  localization,
  midCta,
  related,
  why,
} from "./content";

export const accountingPage = defineOdooPage({
  path: "/odoo/accounting",
  metadata: accountingMetadata,
  breadcrumbLabel: "Accounting & E-Invoicing",
  hero: {
    eyebrow: hero.eyebrow,
    title: hero.title,
    description: hero.description,
    highlight: hero.highlight,
    primary: { label: hero.primary, href: hero.primaryHref },
    secondary: { label: hero.secondary, href: "#core" },
    titleMaxCh: 20,
  },
  anchors,
  sections: [
    {
      type: "section",
      id: "core",
      eyebrow: core.eyebrow,
      title: core.title,
      description: core.description,
      blocks: [{ type: "columns", modules: core.modules }],
    },
    {
      type: "section",
      id: "control",
      tone: "tinted",
      eyebrow: control.eyebrow,
      title: control.title,
      blocks: [{ type: "rows", modules: control.modules }],
    },
    {
      type: "section",
      id: "localization",
      eyebrow: localization.eyebrow,
      title: localization.title,
      description: localization.description,
      blocks: [
        { type: "bullets", items: localization.general },
        {
          type: "flow",
          id: "e-invoicing",
          panel: true,
          columns: 4,
          eyebrow: einvoicing.eyebrow,
          title: einvoicing.title,
          intro: einvoicing.intro,
          steps: einvoicing.steps,
          callout: einvoicing.enterprise || undefined,
          note: einvoicing.note,
          ariaLabel: "How Egypt e-invoicing is set up",
        },
        {
          type: "cards",
          columns: 2,
          items: [
            { title: localization.saudi.title, text: localization.saudi.text },
            { title: localization.uae.title, text: localization.uae.text },
          ],
        },
        { type: "note", text: localization.note },
      ],
    },
    { type: "midCta", title: midCta.title, description: midCta.description },
    {
      type: "section",
      id: "integrations",
      eyebrow: integrations.eyebrow,
      title: integrations.title,
      description: integrations.description,
      blocks: [{ type: "list", items: integrations.items }],
    },
    {
      type: "section",
      id: "comparison",
      tone: "tinted",
      eyebrow: comparison.eyebrow,
      title: comparison.title,
      description: comparison.description,
      blocks: [
        {
          type: "table",
          caption: comparison.caption,
          columns: comparison.columns,
          rows: comparison.rows,
          highlight: 1,
          note: comparison.note,
        },
        { type: "links", items: [comparison.guide] },
      ],
    },
    {
      type: "section",
      id: "why",
      eyebrow: why.eyebrow,
      title: why.title,
      blocks: [{ type: "cards", columns: 3, items: why.cards }],
    },
    {
      type: "strip",
      title: implementation.title,
      description: implementation.description,
      link: {
        text: implementation.link,
        href: "/odoo/implementation",
        ariaLabel: "Read about the Odoo implementation process",
      },
    },
    { type: "faq", id: "faqs", title: "Odoo accounting questions", items: faqs },
    {
      type: "related",
      title: related.title,
      links: [
        { text: related.overview.label, href: related.overview.href },
        {
          text: "Implementation",
          pageKey: "implementation",
          ariaLabel: "Learn more about Odoo Implementation",
        },
        ...related.siblingKeys.map((pageKey) => ({ pageKey })),
      ],
    },
  ],
  closing: {
    title: closing.title,
    description: closing.description,
    secondary: closing.secondary,
  },
});
